import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/_styles/globals.css";
import "@/app/_styles/reset.css";
import "@/app/_styles/font.css";
import "@/app/_styles/animation.css";
import "@/app/_styles/markdown.css";

import HeaderComponent from "./_components/HeaderComponent";
import SidebarLeftComponent from "./_components/SideBarLeftComponent";
import SidebarRightComponent from "./_components/SideBarRightComponent";
import FooterComponent from "./_components/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "this is title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ko">
      <body className={inter.className}>
        <HeaderComponent/>
        <div className="dark-mode flex w-full justify-between bg-zinc-950 h-[92vh] overflow-hidden">
          <SidebarLeftComponent/>
            <div className="w-full overflow-y-scroll customScroll font-spoqa p-8">
              {children}
              <FooterComponent/>
            </div>
          <SidebarRightComponent/>
        </div>
      </body>
    </html>
  );
}
